### ISSUE TITLE
minecraf

### ISSUE THREAD

**Issue by Kabezz** [SheepTester/guestbook#9]
hello guys welcome back to my Minecraft lets play today we're gonna find some diamonds

**Comment by Kabezz** [comment]
uh oh
didn't proccess

**Comment by SheepTester** [comment]
apparently the apostrophe broke it

also now that i think about it, you could probably inject code to run on this repo with that

**Comment by SheepTester** [comment]
i think i fixed it. you can try it again if you'd like

**Comment by Kabezz** [comment]
> apparently the apostrophe broke it
> 
> also now that i think about it, you could probably inject code to run on this repo with that

yeah I was kinda thinking the same thing
